module Validation
  module Limits
    EXPRESSION_MAX_LENGTH = 512
    EXPRESSION_MAX_TOKENS = 256
    EXPRESSION_MAX_DEPTH = 64
    EVALUATION_MAX_OPERATIONS = 1_024
    SAMPLE_COUNT = 12
    MAX_SAMPLE_ATTEMPTS = SAMPLE_COUNT * 3
    EXPRESSION_TIMEOUT_SECONDS = 0.1
  end
end
